### ISSUE TITLE
Añadir atributo edad y metodo toString

### ISSUE THREAD

**Issue by jonh88** [jonh88/IWVG.SwC.jonh88#3]
Se trata de añadir el atributo edad a la clase User y el método toString.
Más información en la [wiki](../wiki/User#ampliaci%C3%B3n-de-funcionalidad)

**Comment by asancgom** [comment]
He añadido el atributo edad, modificando el constructor para que inicialice este nuevo atributo y el método toString() . Todo probado con los correspondientes test.
